// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUdK2X2zrCf067bLlrDVlYDBjpcvdDsQ4',
    appId: '1:518854918230:web:555723c9131b71956abbf7',
    messagingSenderId: '518854918230',
    projectId: 'organise-me-8aef0',
    authDomain: 'organise-me-8aef0.firebaseapp.com',
    storageBucket: 'organise-me-8aef0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeYuT7Y-JIcOIXr4AaY9Q-qVpXOY9BB6E',
    appId: '1:518854918230:android:98a84ebdc312b7726abbf7',
    messagingSenderId: '518854918230',
    projectId: 'organise-me-8aef0',
    storageBucket: 'organise-me-8aef0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2gz1jDeqEEj3_318D9thRSmeTgVMHg0Q',
    appId: '1:518854918230:ios:6ad5537035b259d46abbf7',
    messagingSenderId: '518854918230',
    projectId: 'organise-me-8aef0',
    storageBucket: 'organise-me-8aef0.appspot.com',
    iosClientId: '518854918230-jmomnkqnms7clbpa604s4gin4mmaeeuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.organiseMe',
  );
}
